services:
  ex-dash:
    build:
      context: .
      dockerfile: ./apps/ex-dash/Dockerfile
    ports:
      - 8080:3000
    networks:
      - local

  ex-products:
    depends_on:
      - ex-dash
    build:
      context: .
      dockerfile: ./apps/ex-products/Dockerfile
    ports:
      - 3010:3000
    networks:
      - local

networks:
  local:
